Inventario/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from inventario_app.views import inventario_app, administrador, soporte, laboratorio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventario_app.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', inventario_app.SignUpView.as_view(), name='signup'),
    path('accounts/signup/administrador/', administrador.AdministradorSignUpView.as_view(), name='administrador_signup'),
    path('accounts/signup/laboratorio/', laboratorio.LaboratorioSignUpView.as_view(), name='laboratorio_signup'),
    path('accounts/signup/soporte/', soporte.SoporteSignUpView.as_view(), name='soporte_signup'),


    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventario_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from .views import inventario_app, administrador, soporte, laboratorio

urlpatterns = [
    path('', inventario_app.home, name='home'),

    path('administrador/', include(([
        path('', administrador.index, name='index'),
        path('despacho/<int:pk>/reporte_todos_excel/',administrador.ReporteTodosExcel.as_view(), name="reporte_todos_excel"),
        path('insumo/BCAM', administrador.insumo_list, name='BCAM'),
        path('insumo/index', administrador.insumo_index, name='insumo_index'),
        path('insumo/CSAB/', administrador.baluarte, name='CSAB'),
        path('insumo/BCM/', administrador.bc_maipu, name='BCM'),
        path('insumo/BCLF/',administrador.bc_farfana, name='BCLF'),
        path('insumo/CEB/',administrador.el_bosque, name='CEB'),
        path('insumo/CICV/',administrador.inmaculada_vitacura, name='CICV'),
        path('insumo/CLA/',administrador.los_alpes, name='CLA'),
        path('insumo/CMAN/',administrador.manantial, name='CMAN'),
        path('insumo/CSE/',administrador.sebastian_alcano, name='CSE'),
        path('insumo/CSFP/',administrador.san_francisco, name='CSFP'),
        path('insumo/CSM/',administrador.san_marcos, name='CSM'),
        path('insumo/IOM/',administrador.iom, name='IOM'),
        path('insumo/SSLA/',administrador.san_sebastia, name='SSLA'),
        path('insumo/add/', administrador.crear_insumo, name='insumo_form'),
        path('actividad/', administrador.actividad, name='actividad'),
        path('reportes/', administrador.reportes, name='reportes'),
        path('reportes/add/', administrador.crear_reporte, name='reporte_add'),
        path('reportes/<int:pk>/reportes_new/add/', administrador.crear_reporte_new, name='reporte_new_add'),
        path('reportes/<int:pk>', administrador.reportes_view, name='reportes_view'),
        path('inventario/<int:pk>/despacho/add/', administrador.crear_despacho, name='despacho'),
        path('despacho/', administrador.despacho, name='despacho_list'),
        path('despacho/<int:pk>', administrador.despacho_detail, name='despacho_detail'),
        path('usuarios/', administrador.usuarios, name='usuarios'),
        path('inventario/add/', administrador.crear_inventario, name='inventario_add'),
        path('inventario/<int:pk>/update', administrador.change_inventario, name='editar_inventario'),
        path('inventario/<int:pk>/delete/', administrador.InventarioDeleteView.as_view(), name='inventario_delete'),
        path('inventario/<int:pk>', administrador.descripcion, name='inventario_detalle'),
        path('inventario/<int:pk>/adicional/add/', administrador.crear_adicional, name='adicional_add'),
        path('inventario/<int:inventario_pk>/adicional/<int:adicional_pk>/', administrador.adicional_change, name='adicional_edit'),
        path('inventario/<int:pk>/monitor/add/', administrador.crear_monitor, name='monitor_add'),
        path('inventario/<int:inventario_pk>/monitor/<int:monitor_pk>/', administrador.monitor_change, name='monitor_edit'),
        path('inventario/<int:inventario_pk>/monitor/<int:monitor_pk>/delete/', administrador.MonitorDeleteView.as_view(), name='monitor_delete'),
        path('inventario/<int:pk>/incidencia/add/', administrador.crear_incidencia, name='incidencia_add'),


    ], 'inventario_app'), namespace='administrador')),

    path('soporte/', include(([
        path('', soporte.index, name='index'),
        path('reportes/', soporte.reportes, name='reportes'),
        path('reportes/add/', soporte.crear_reporte, name='reporte_add'),
        path('reportes/<int:pk>/reportes_new/add/', soporte.crear_reporte_new, name='reporte_new_add'),
        path('reportes/<int:pk>', soporte.reportes_view, name='reportes_view'),
        path('inventario/add/', soporte.CrearInventarioView.as_view(), name='inventario_add'),
        path('inventario/<int:pk>', soporte.descripcion, name='inventario_detalle'),
        path('inventario/<int:pk>/adicional/add/', soporte.crear_adicional, name='adicional_add'),
        path('inventario/<int:pk>/monitor/add/', soporte.crear_monitor, name='monitor_add'),
        path('inventario/<int:pk>/incidencia/add/', soporte.crear_incidencia, name='incidencia_add'),        
    ], 'inventario_app'), namespace='soporte')),
    
    path('laboratorio/', include(([
        path('', laboratorio.index, name='index'),
        path('reportes/', laboratorio.reportes, name='reportes'),
        path('reportes/add/', laboratorio.crear_reporte, name='reporte_add'),
        path('reportes/<int:pk>/reportes_new/add/', laboratorio.crear_reporte_new, name='reporte_new_add'),
        path('reportes/<int:pk>', laboratorio.reportes_view, name='reportes_view'),
        path('inventario/add/', laboratorio.CrearInventarioView.as_view(), name='inventario_add'),
        path('inventario/<int:pk>', laboratorio.descripcion, name='inventario_detalle'),
        path('inventario/<int:pk>/adicional/add/', laboratorio.crear_adicional, name='adicional_add'),
        path('inventario/<int:pk>/monitor/add/', laboratorio.crear_monitor, name='monitor_add'),
        path('inventario/<int:pk>/incidencia/add/', laboratorio.crear_incidencia, name='incidencia_add'),
    ], 'inventario_app'), namespace='laboratorio')),
    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventario_app/models.py
import sys
import math
import random
from io import BytesIO
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe
from model_utils.managers import InheritanceManager
from django.utils.timezone import utc
from simple_history.models import HistoricalRecords

# Create your models here.



class User(AbstractUser):
    is_administrador = models.BooleanField(default=False)
    is_soporte = models.BooleanField(default=False)
    is_laboratorio = models.BooleanField(default=False)


def colegios_images(instance, filename):
    return 'UserImages/user_{0}/{1}'.format(instance.user.id, filename)

def inventario_images(instance, filename):
    return 'UserImages/user_{0}/{1}'.format(instance.user.id, filename)

def monitor_images(instance, filename):
    return 'UserImages/user_{0}/{1}'.format(instance.user.id, filename)

class Colegios(models.Model):
    name = models.CharField(max_length=250)
    imagen = models.ImageField( null = True, upload_to='colegios_images',default=False, blank=True,verbose_name=('Imagen'), unique=True)

    def __str__(self):
        return self.name

class Insumos(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Marca(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Equipo(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Extras(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Condicion(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Administrador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    colegio = models.ManyToManyField(Colegios, related_name='colegio_administrador')

    def __str__(self):
        return self.user.username

class Soporte(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    colegio = models.ManyToManyField(Colegios, related_name='colegio_soporte')
    
    def __str__(self):
        return self.user.username
        
class Laboratorio(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    colegio = models.ManyToManyField(Colegios, related_name='colegio_laboratorio')
    
    def __str__(self):
        return self.user.username

class Insumoform(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=('Usuario'))
    insumo = models.ForeignKey(Insumos, on_delete=models.CASCADE, verbose_name=('Insumo')) 
    colegio = models.ForeignKey(Colegios, on_delete=models.CASCADE)
    factura = models.CharField(max_length=250)
    cantidad = models.FloatField(default=0)
    fecha = models.DateField(auto_now_add=False,auto_now=False, verbose_name='Fecha de compra')
    proveedor = models.CharField(max_length=250)
    def __str__(self):
        return self.insumo.name


class Insumo_Egreso(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=('Usuario'))
    insumo = models.ForeignKey(Insumos, on_delete=models.CASCADE, verbose_name=('Insumo'))
    cantidad = models.FloatField(default=0)

    def __str__(self):
        return self.insumo.name
    
class Inventario(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=('Usuario'))
    codigo = models.CharField(max_length=250, verbose_name=('Codigo de equipo'), help_text='Ejemplo: PC001')
    colegio = models.ForeignKey(Colegios, on_delete=models.CASCADE)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    modelo = models.CharField(max_length=250)
    serie = models.CharField(max_length=250)
    numero_doc = models.CharField(max_length=250, verbose_name=('N° de documento'), help_text='Puede ser el número de factura, boleta, etc',null=True, blank=True)
    Fecha = models.DateField(auto_now_add=False,auto_now=False, verbose_name='Fecha de compra')
    ubicacion = models.CharField(max_length=250)
    usuario = models.CharField(max_length=500, verbose_name=('Usuario Responsable'))
    valido = models.BooleanField(null= False, default=True, verbose_name=('validar'), help_text='Cuando esta activa esta opción el formulario estara válido.')
    imagen = models.ImageField(  upload_to='inventario_images', verbose_name=('Imagen'))
    condicion = models.ForeignKey(Condicion, on_delete=models.CASCADE ,verbose_name=('Condición'))

    history = HistoricalRecords()


    def save_without_historical_record(self, *args, **kwargs):
        self.skip_history_when_saving = True
        try:
            ret = self.save(*args, **kwargs)
        finally:
            del self.skip_history_when_saving
        return ret

    def __str__(self):
        return str(self.id)

    def delete(self, *args, **kwargs):
        self.imagen.delete()
        super().delete(*args, **kwargs)

class Images(models.Model):
    inventario = models.ForeignKey(Inventario, on_delete=models.CASCADE)
    image = models.ImageField( upload_to='inventario_images', verbose_name=('Imagen'), blank=True, null=True)

    def __str__(self):
        return str(self.inventario.id)

class Adicional(models.Model):
    inventario = models.ForeignKey(Inventario, on_delete=models.CASCADE, related_name='inventarios')
    procesador = models.CharField(max_length=250)
    ram = models.CharField(max_length=250)
    sistema = models.CharField(max_length=250, help_text='Sistema operativo')
    disco = models.CharField(max_length=250)
    placa = models.CharField(max_length=250, help_text='Placa Madre')
    office = models.CharField(max_length=250, blank=True, null=True)
    history = HistoricalRecords()


    def save_without_historical_record(self, *args, **kwargs):
        self.skip_history_when_saving = True
        try:
            ret = self.save(*args, **kwargs)
        finally:
            del self.skip_history_when_saving
        return ret

    def __str__(self):
        return str(self.inventario_id)

class Monitor(models.Model):
    inventario = models.ForeignKey(Inventario, on_delete=models.CASCADE, related_name='monitores')
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    modelo = models.CharField(max_length=250)
    serie = models.CharField(max_length=250)
    imagen = models.ImageField( null = True, upload_to='monitor_images', blank=True,verbose_name=('Imagen'))
    history = HistoricalRecords()

    def save_without_historical_record(self, *args, **kwargs):
        self.skip_history_when_saving = True
        try:
            ret = self.save(*args, **kwargs)
        finally:
            del self.skip_history_when_saving
        return ret

    def __str__(self):
        return self.modelo
    
    def delete(self, *args, **kwargs):
        self.imagen.delete()
        super().delete(*args, **kwargs)

class Incidencia(models.Model):
    inventario = models.ForeignKey(Inventario, on_delete=models.CASCADE, related_name='incidencias')
    texto = models.TextField(max_length=5000)
    created = models.DateField(auto_now_add=True)
    history = HistoricalRecords()


    def save_without_historical_record(self, *args, **kwargs):
        self.skip_history_when_saving = True
        try:
            ret = self.save(*args, **kwargs)
        finally:
            del self.skip_history_when_saving
        return ret

    def __str__(self):
        return self.texto


class Reporte(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    colegio = models.ForeignKey(Colegios, on_delete=models.CASCADE)
    texto = models.TextField(max_length=5000)
    created = models.DateField(auto_now_add=True)
    tiempo = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()


    def save_without_historical_record(self, *args, **kwargs):
        self.skip_history_when_saving = True
        try:
            ret = self.save(*args, **kwargs)
        finally:
            del self.skip_history_when_saving
        return ret

    def __str__(self):
        return self.texto

class ReporteNew(models.Model):
    reporte = models.ForeignKey(Reporte, on_delete=models.CASCADE)
    texto = models.TextField(max_length=5000)
    tiempo = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()


    def save_without_historical_record(self, *args, **kwargs):
        self.skip_history_when_saving = True
        try:
            ret = self.save(*args, **kwargs)
        finally:
            del self.skip_history_when_saving
        return ret
        
    def __str__(self):
        return self.texto


class Despacho(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name=('Usuario'))
    usuario = models.CharField(max_length=250, verbose_name=('Usuario'))
    area = models.CharField(max_length=250)
    origen = models.ForeignKey(Colegios, on_delete=models.CASCADE, related_name='origen')
    solicitado = models.CharField(max_length=250)
    fecha_entrega = models.DateTimeField(auto_now_add=False,auto_now=False, verbose_name='Fecha de entrega')
    fecha = models.DateField(auto_now_add=True)
    destino = models.ForeignKey(Colegios, on_delete=models.CASCADE, related_name='destino')
    equipo = models.ForeignKey(Inventario, on_delete=models.CASCADE)
    extras = models.ManyToManyField(Extras, related_name='extras')
    history = HistoricalRecords()

    def save_without_historical_record(self, *args, **kwargs):
        self.skip_history_when_saving = True
        try:
            ret = self.save(*args, **kwargs)
        finally:
            del self.skip_history_when_saving
        return ret
    
    def __str__(self):
        return str(self.id)

inventario_app/templates/inventario_app/administrador/inventario/descripcion.html
{% load static %}
{% load crispy_forms_tags %}

{% if user.is_authenticated and user.is_administrador %}
<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <link rel="stylesheet" type="text/css" href="{% static "vendor/fontello-2f186091/css/fontello.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/animations.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/administrador.css" %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


    <title>Administrador</title>
    <meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>
<body>
    <nav class="navbar  fixed-top  flex-md-nowrap p-0 " style="background-color: #0D32B1;">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href='/' style="color: white;" >Departamento Informática</a>
        <ul class="navbar-nav px-3">
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'logout' %}" style="color: white;">Salir</a>
          </li>
        </ul>
      </nav>
          <div class="container-fluid">
            <div class="row">
              <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <img    src="{% static "img/logo.jpg" %}"  class="img-thumbnail" style="width:230px;height:70px;"  alt="">

                <div class="sidebar-sticky">
                  <ul class="nav flex-column">
                    <li class="nav-item">
                      <a class="nav-link active" href="/">
                        <i class="fas fa-table"></i>
                        Inventario 
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'administrador:actividad' %}">
                        <i class="fas fa-clipboard-list"></i>
                        Actividad
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'administrador:reportes' %}">
                        <i class="far fa-file-alt"></i>
                        Reportes Diarios
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'administrador:usuarios' %}">
                        <i class="fas fa-users"></i>                   
                        Usuarios
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'administrador:despacho_list' %}">
                          <i class="fas fa-dolly"></i>   
                          Movimientos
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link " href="{%url 'administrador:insumo_index' %}">
                        <i class="fas fa-desktop"></i>
                          Insumos
                      </a>
                  </li>         
                  </ul>
          
              <!--    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Departamento de informática</span>
                    <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                      <span data-feather="plus-circle"></span>
                    </a>
                  </h6> -->
                </div>
              </nav>
          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Detalle</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                  <div class="btn-group mr-2">
                    <a href="{% url 'administrador:despacho' inventario.pk %}" class="btn btn-sm btn-outline-secondary">Agregar Nuevo movimiento</a>

                    <a href="{% url 'administrador:adicional_add' inventario.pk %}" class="btn btn-sm btn-outline-secondary">Agregar caracteristicas</a>
                    <a href="{% url 'administrador:monitor_add' inventario.pk %}" class="btn btn-sm btn-outline-secondary">Agregar monitor</a>
                    <a href="{% url 'administrador:incidencia_add' inventario.pk %}" class="btn btn-sm btn-outline-secondary">Agregar incidencia</a>

                  </div>
                  
                </div>
            </div>
      
            


            <div class="row mb-2">
                <div class="col-md-6">
                  <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <div class="container-fluid" >
                          {% if inventario.colegio.imagen %}
                          <img src=" {{inventario.colegio.imagen.url}} " alt="" class="float-right" style="width: 40%;">
                          {% endif %}
                            <p class="text-muted">Agregado por: {{inventario.user}} </p>
                          <br>
                            <p style="text-transform: uppercase;"> <strong> Codigo:</strong> {{inventario.codigo}}</p>
                            <p> <strong> Equipo:</strong> {{inventario.equipo}}</p>
                            <p><strong>Usuario:</strong> {{inventario.usuario}} </p>
                            <p> <strong>Colegio:</strong> {{inventario.colegio}}</p>
                            <p><strong>Modelo:</strong> {{inventario.modelo}}</p>
                            <p><strong>Marca:</strong> {{inventario.marca}} </p>
                            <p><strong>N° Documento:</strong> {{inventario.numero_doc}} </p>
                            <p><strong>Fecha de compra:</strong> {{inventario.Fecha|date:"d/m/Y"}} </p>
                            <p><strong>Serie:</strong> {{inventario.serie}} </p>
                            <p><strong>Ubicación:</strong> {{inventario.ubicacion}} </p>
                            <p><strong>Condición</strong> {{inventario.condicion}} </p>
                            <p><strong>Estado:</strong> {% if inventario.valido == True %} <span style="color: blue;"> Válido </span>{% else %} {% if inventario.valido == False %} <span style="color: red;"> Nulo </span>{% endif %} {% endif %} </p>
                            <br>
                            <a href="{% url 'administrador:editar_inventario' inventario.pk %}" class="btn btn-sm btn-primary">Editar inventario</a>

                            <br>
                            <hr>
                            <h4> <strong>Incidencia</strong> </h4>
                            {% for incidencia in incidencia %}
                             <p class="text-justify" style="white-space: pre-wrap; ">{{incidencia.created|date:"d/m/Y"}} {{incidencia.texto}}</p> 
                            {% endfor %}
                        </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    {% if inventario.imagen %}
                      <a href="{{ inventario.imagen.url }}" target="_blank"><img src="{{ inventario.imagen.url }}"  class="img-fluid border border-dark "></a>
                    {% endif %}
                    <div class="row gallery">
                      {% for p in inventario.images_set.all %}
                      {% if p.image %}
                        <div class="col-md-6">
                          <a href="{{ p.image.url }}" target="_blank"><img src="{{ p.image.url }}" alt="Image Not Found" class="img-thumbnail"></a>
                        </div>
                      {% endif %}
                      {% endfor %}
                    </div>
  
                  </div>
                </div>
            </div>

            <div class="table-responsive">
              <h3>Caracteristicas</h3>
                <table class="table table-striped table-sm">
                  <thead>
                    <tr>
                      <th>Procesador</th>
                      <th>Ram</th>
                      <th>Sistema</th>
                      <th>Disco</th>
                      <th>Placa Madre</th>
                      <th>Office</th>
                      <th></th>
  
                    </tr>
                  </thead>
                  <tbody>
                    {% for adicional in adicional %}
                    <tr>
                      <td>{{adicional.procesador}}</td>
                      <td>{{adicional.ram}}</td>
                      <td>{{adicional.sistema}}</td>
                      <td>{{adicional.disco}}</td>
                      <td>{{adicional.placa}}</td>
                      <td>{{adicional.office}}</td>
                      <td class="text-right">
  
                        <a href="{% url 'administrador:adicional_edit' inventario.pk adicional.pk %}" class="btn btn-sm btn-primary">Editar</a>
          
                        
                      </td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td class="bg-light text-center font-italic" colspan="5">No tiene caracteristicas todavia</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            </div>

            <div class="table-responsive">
              <h3>Monitor</h3>
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th>Marca</th>
                    <th>Modelo</th>
                    <th>Serie</th>
                    <th>Imagen</th>
                    <th></th>

                  </tr>
                </thead>
                <tbody>
                {% for monitor in monitor %}
                  <tr>
                    <td>{{monitor.marca}}</td>
                    <td>{{monitor.modelo}}</td>
                    <td>{{monitor.serie}}</td>
                  {% if monitor.imagen %}
                    <td><a href="{{ monitor.imagen.url }}" target="_blank">Ver</a></td>
                    {% endif %}
                    <td class="text-right">

                      <a href="{% url 'administrador:monitor_edit' inventario.pk monitor.pk %}" class="btn btn-sm btn-primary">Editar</a>
        
                      
                    </td>
                  </tr>
                  {% empty %}
                  <tr>
                    <td class="bg-light text-center font-italic" colspan="5">No tiene monitor todavia</td>
                  </tr>
                 
                {% endfor %}
                </tbody>
              </table>
          </div>
            

            <br>
<br>

              <br>
          </main>
        </div>
      </div>
{% endif %}
</body>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static "js/jquery.plugin.min.js" %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js" integrity="sha256-o8aByMEvaNTcBsw94EfRLbBrJBI+c3mjna/j4LrfyJ8=" crossorigin="anonymous"></script>    


</html>